import * as Dashboard from './dashboard'
import * as Errors from './errors'
import * as Auth from './auth'
import * as Profile from './profile'
import * as Staffs from './staffs'
import * as Categories from './categories'
import * as Brands from './brands'
import * as Customers from './customers'
import * as Hotels from './hotels'
import * as Reviews from './reviews'
import * as Bookings from './bookings'
import * as Rooms from './rooms'
import * as OrderDetails from './orderDetails'

export { Dashboard, Errors, Auth, Profile, Staffs, Categories, Brands, Customers, Hotels, Reviews, Bookings, Rooms, OrderDetails }